services:
  data-server:
    build:
      context: .
      dockerfile: data_server/Dockerfile
    ports:
      - "9001:9001"
    environment:
      DATA_SWITCHES: "64"
      DATA_INTERVAL_SEC: "10"
      FAULT_500_PCT: "0"
      FAULT_SLOW_MS: "0"

  metrics-server:
    build:
      context: .
      dockerfile: metrics_server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      UPSTREAM_URL: "http://data-server:9001/counters"
      POLL_MS: "1500"
      LOG_LEVEL: "INFO"
    depends_on:
      - data-server
