version: "3.8"
services:
  data-server:
    build: ./data_server
    ports: ["9001:9001"]
    environment:
      DATA_SWITCHES: "64"
      DATA_INTERVAL_SEC: "10"
      FAULT_500_PCT: "0"
      FAULT_SLOW_MS: "0"

  metrics-server:
    build: ./metrics_server
    ports: ["8080:8080"]
    environment:
      UPSTREAM_URL: "http://data-server:9001/counters"
      POLL_MS: "1500"
      LOG_LEVEL: "INFO"
    depends_on:
      - data-server
